print('What do you get when you cross a snowman with a vampire?')
answer = input()
print("You guessed: " + answer)
print('The real answer was: Frostbite!')
input()
print('What do dentists call a astronaut\'s cavity?')
print('A \nblack \nhole!')
input()
print('Knock knock.')
print("Who's there?")
print('Interrupting cow.')
print('Interrupting cow wh', end='')
print('-MOO!')
input()
print("Why did math look so sad?")
print("Because of all its problems.")
input()
print("What did the slow tomato say to the others?".upper())
print("Don\'t worry; I'll ketchup.".lower())
input()
print("How do celebrities stay cool?")
print("\"They have lots of fans.\"")